function Get-AppIdPlaceholderColor {
    if ($script:IsDarkMode) {
        return [System.Drawing.Color]::FromArgb(160, 160, 160)
    }

    return [System.Drawing.Color]::FromArgb(130, 130, 130)
}

function Get-RealAppIdValue {
    if (-not $txtAppId) { return '' }
    if ($txtAppId.Tag -eq 'PLACEHOLDER') { return '' }
    return $txtAppId.Text.Trim()
}

function Get-AutoGeneratedAppIdFromName {
    param([string]$Name)

    if ([string]::IsNullOrWhiteSpace($Name)) {
        return 'com.company.appname'
    }

    $clean = $Name.ToLower() -replace '[^a-z0-9]', ''
    if ([string]::IsNullOrWhiteSpace($clean)) {
        $clean = 'appname'
    }

    return "com.company.$clean"
}

function Set-AppIdPlaceholder {
    if (-not $txtAppId) { return }

    $script:IsUpdatingAppIdProgrammatically = $true
    $txtAppId.Tag = 'PLACEHOLDER'
    $txtAppId.Text = 'com.company.appname'
    $txtAppId.ForeColor = Get-AppIdPlaceholderColor
    $script:IsUpdatingAppIdProgrammatically = $false
}

function Clear-AppIdPlaceholder {
    if (-not $txtAppId) { return }

    if ($txtAppId.Tag -eq 'PLACEHOLDER') {
        $script:IsUpdatingAppIdProgrammatically = $true
        $txtAppId.Text = ''
        if ($script:IsDarkMode) {
            $txtAppId.ForeColor = $script:DarkColorText
        } else {
            $txtAppId.ForeColor = $script:ColorText
        }
        $txtAppId.Tag = $null
        $script:IsUpdatingAppIdProgrammatically = $false
    }
}

function Update-AppIdFromAppName {
    if (-not $txtAppId -or -not $txtAppName) { return }

    if ($script:AppIdManuallyEdited) { return }

    $newValue = Get-AutoGeneratedAppIdFromName $txtAppName.Text.Trim()
    $script:IsUpdatingAppIdProgrammatically = $true
    $txtAppId.Tag = 'AUTO'
    $txtAppId.Text = $newValue
    if ($script:IsDarkMode) {
        $txtAppId.ForeColor = $script:DarkColorText
    } else {
        $txtAppId.ForeColor = $script:ColorText
    }
    $script:IsUpdatingAppIdProgrammatically = $false
}